### ISSUE TITLE
Brew Install fail

### ISSUE THREAD

**Issue by jeanbapt** [paritytech/homebrew-paritytech#30]
Hello, I have an updated brew, and parity fails to install / reinstall.

I get this :

`==> Reinstalling ethcore/ethcore/parity
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/jeanbapt/Library/Caches/Homebrew/parity--git
==> Checking out branch stable
error: no such remote ref 403ff2e4759577d9e2b75b1389787a9c29670736
Fetched in submodule path 'ethcore/res/ethereum/tests', but it did not contain 403ff2e4759577d9e2b75b1389787a9c29670736. Direct fetching of that commit failed.
Error: Failed to download resource "parity"
Failure while executing: git submodule -q update --init --recursive
`

**Comment by debris** [comment]
we use prebuilt binaries now, closing
