### ISSUE TITLE
Multirust is no longer maintained, author recommends rustup

### ISSUE THREAD

**Issue by taoeffect** [paritytech/homebrew-paritytech#33]
Basically the title. But a better option might be to just let homebrew take care of upgrading rust via its rust formula.

Relying on either multirust and rustup would mean that people who have rust managed by homebrew cannot install parity, as it results in a conflict like this:

```
-> % brew install parity
==> Installing parity from ethcore/ethcore
==> Installing dependencies for ethcore/ethcore/parity: multirust
==> Installing ethcore/ethcore/parity dependency: multirust
Error: Cannot install multirust because conflicting formulae are installed.

  rust: because both install rustc, rustdoc, cargo, rust-lldb, rust-gdb

Please `brew unlink rust` before continuing.
```

**Comment by debris** [comment]
>  But a better option might be to just let homebrew take care of upgrading rust via its rust formula.

I strongly disagree. This would break existing installations for everyone who already have parity. Also, it was `multirust`, not `rust` formula which was a recommended way to install rust.

We will switch to `rustup` as soon as someone prepares brew formula for it [issue #5263](https://github.com/Homebrew/homebrew-core/issues/5263). I believe the same pr will deprecate `multirust`

**Comment by taoeffect** [comment]
> I strongly disagree. This would break existing installations for everyone who already have parity.

How? It's a binary. Once you build it it's built. If there's an issue with homebrew, the brew formula could probably be updated with a migration script (if needed).
