### ISSUE TITLE
SHA256 mismatch on beta

### ISSUE THREAD

**Issue by hellominotaur** [paritytech/homebrew-paritytech#43]
```
Expected: 6700743239f6aa4b2b7a2d8b9a98ddab22f7362be827c4a54cccd65e74bcd692
Actual: 65b32bd3178f442ddd9e2eb24d04ba16a6dad933f46ad7fec215900fa9358cfb
```

[Looks like](https://github.com/paritytech/homebrew-paritytech/commit/b1ae251a15d27988bbec1c227b6a2b3ef4ff04f9#diff-fff9fb419821ac2bc1e37ce7ae3e1487) the digests weren't updated with the versions yesterday

**Comment by marekkirejczyk** [comment]
Same here.

**Comment by hellominotaur** [comment]
Can see its downloading correctly now. Cheers.
