### ISSUE TITLE
Homebrew fails to install Eth ABI - Multirust is deprecated.

### ISSUE THREAD

**Issue by hairychris** [paritytech/homebrew-paritytech#44]
```
$ brew install paritytech/paritytech/ethabi
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing ethabi from paritytech/paritytech
Error: No available formula with the name "multirust" (dependency of paritytech/paritytech/ethabi)
==> Searching for a previously deleted formula...
multirust was deleted from homebrew/core in commit b5d9de6:
  multirust: remove (https://github.com/Homebrew/homebrew-core/issues/11810)

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show b5d9de6^:Formula/multirust.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
2.17s user 3.37s system 75% cpu 7.378s total
```

Is it worth creating a tap or dropping support for multirust and using something else?

**Comment by debris** [comment]
That's unfortunate that multirust has been removed without any replacement :/ I will see what we can do about this problem. In the meantime, you can install manually using cargo

```
# install rustup
curl https://sh.rustup.rs -sSf | sh
# install ethabi
cargo install --git https://github.com/paritytech/ethabi.git --features="cli"
```

**Comment by ajbhatia-visa** [comment]
I tried installing `ethabi` with the two commands above. The `curl` command to install `rustup` ran successfully, but the `cargo install` gave the following error about not having `cli` feature :

    %> cargo install --git https://github.com/paritytech/ethabi.git --features="cli"
    Updating git repository `https://github.com/paritytech/ethabi.git`
    Installing ethabi-cli v2.0.1 (https://github.com/paritytech/ethabi.git#04fd68f0)
    error: failed to compile `ethabi-cli v2.0.1 (https://github.com/paritytech/ethabi.git#04fd68f0)`,
    intermediate artifacts can be found at `/var/folders/rk/klf1ymwn5dj6dyff2kl0cwpd2__dr7/T/cargo-install.p8Gw4vAOMYYK`

    Caused by:
      Package `ethabi-cli v2.0.1 (https://github.com/paritytech/ethabi.git#04fd68f0)` does not have these features: `cli`

Any suggestions?

**Comment by debris** [comment]
actually build step for `ethabi` has changed recently. now it's:

```sh
cargo install --git https://github.com/paritytech/ethabi.git ethabi-cli
```
