### ISSUE TITLE
OS X GUI and Install

### ISSUE THREAD

**Issue by IwanHopka** [paritytech/homebrew-paritytech#48]
HI, Installer didn't work on Yosemite so I tried the bash command: 
bash <(curl https://get.parity.io -Lk)

Things were and are happening (it is syncing i think) but this message appeared:

`` Warning: Calling build.build_bottle? is deprecated!
Use build.bottle? instead.
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:37:in `reinstall_formula'

==> Reinstalling paritytech/paritytech/parity 
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.6.7/x86_64-apple-darwin/
######################################################################## 100.0%
==> Caveats
To have launchd start paritytech/paritytech/parity now and restart at login:
  brew services start paritytech/paritytech/parity
==> Summary
🍺  /usr/local/Cellar/parity/1.6.7: 4 files, 30.8MB, built in 19 seconds
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks."

I can not see Parity in my Applications folder. What to do? 
thanks. I'm a parity noob so be gentle

**Comment by 5chdn** [comment]
run `parity` in your terminal
