### ISSUE TITLE
Is parity available in CMD + SPACE menu?

### ISSUE THREAD

**Issue by stefek99** [paritytech/homebrew-paritytech#53]
Installed parity via installer on a loaner laptop.

Installed parity via brew on my main machine.

I cannot `cmd + space` to launch parity on my main machine.

`brew uninstall --force parity` and install via installer.

Is it much trouble to be compatible with `cmd + space` when using brew?

_(or maybe I've completely messed up something, in that case please ignore me)_

**Comment by 5chdn** [comment]
> Is it much trouble to be compatible with cmd + space when using brew?

yes. :)

Just use the installer and symlink the parity binary or add the parity binary to your path
