### ISSUE TITLE
how can i check the binary downloaded is not malicious ?

### ISSUE THREAD

**Issue by ezredd** [paritytech/homebrew-paritytech#57]
I am using Mac and currently parity seems to only provide the checksum for the parity pkg installer.

If i want to install parity using homebrew instead is there a way i can verify that the downloaded binary is not malicious ?

It would be great if parity could publish the checksum for the payload downloaded by homebew.

thanks!

**Comment by 5chdn** [comment]
homebrew is checking the integrity via SHA256 automatically.
