### ISSUE TITLE
cant execute my transfer for my cobinhood tokens

### ISSUE THREAD

**Issue by thebigskinny** [paritytech/homebrew-paritytech#66]
txhash: 0x957dafdfccbb5675273ee3029370fc0fd89dc59551dae4204311d41a16826a41 

I'm trying to execute my transfer. I followed the instructions that were given;

execute
transfer to from
entered my account the address of my cobinhood wallet to send to
I did a small test amount of 20 tokens and I keep getting a fail due to bad instructions.

please help

**Comment by 5chdn** [comment]
Can you try providing more gas?
