### ISSUE TITLE
Always tries to upgrade on latest stable release

### ISSUE THREAD

**Issue by k06a** [paritytech/homebrew-paritytech#70]
Already have 1.8.10 installed:
```
$ brew upgrade --verbose
```
```
==> Upgrading 4 outdated packages, with result:
paritytech/paritytech/parity 1.9.3, godep 80_2, gradle 4.5.1, git 2.16.2
==> Upgrading paritytech/paritytech/parity --stable
rm /usr/local/bin/parity
/usr/bin/sandbox-exec -f /tmp/homebrew20180223-25547-1bwf20x.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech/parity.rb --verbose --stable
==> Downloading https://d1h4xl4cr1h0mo.cloudfront.net/v1.8.10/x86_64-apple-darwin/parity
Already downloaded: /Users/k06a/Library/Caches/Homebrew/parity-1.8.10
==> Verifying parity-1.8.10 checksum
ln -s ../Cellar/parity/1.8.10/bin/parity parity
Error: Empty installation
```

**Comment by 5chdn** [comment]
Please remove parity and install it again.

**Comment by k06a** [comment]
@5chdn I tried this a lot of times

**Comment by k06a** [comment]
@5chdn please, reopen the issue.

**Comment by k06a** [comment]
```
$ brew outdated
```
```
paritytech/paritytech/parity (1.8.10) < 1.9.3
```
But 1.9.3 is not `--stable` yet.

**Comment by 5chdn** [comment]
please try again with:

    brew upgrade --verbose

and share the logs here please

**Comment by k06a** [comment]
Looks like issue is closely related to https://github.com/paritytech/homebrew-paritytech/issues/62

**Comment by k06a** [comment]
```
$ brew upgrade --verbose
```
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (paritytech/paritytech).
No changes to formulae.

==> Upgrading 1 outdated package, with result:
paritytech/paritytech/parity 1.9.3
==> Upgrading paritytech/paritytech/parity --stable
rm /usr/local/bin/parity
/usr/bin/sandbox-exec -f /tmp/homebrew20180228-70274-1505oay.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech/parity.rb --verbose --stable
==> Downloading https://d1h4xl4cr1h0mo.cloudfront.net/v1.8.11/x86_64-apple-darwin/parity
/usr/bin/curl --show-error --user-agent Homebrew/1.5.5 (Macintosh; Intel Mac OS X 10.13.3) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/k06a/Library/Caches/Homebrew/parity-1.8.11.11.incomplete https://d1h4xl4cr1h0mo.cloudfront.net/v1.8.11/x86_64-apple-darwin/parity
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.2M  100 38.2M    0     0  4966k      0  0:00:07  0:00:07 --:--:-- 7921k
==> Verifying parity-1.8.11.11 checksum
ln -s ../Cellar/parity/1.8.10/bin/parity parity
Error: Empty installation
```

**Comment by 5chdn** [comment]
!?! god on earth, please help me. there are so many issues in this log I do not understand:

Why does it try to upgrade to 1.9.3, then downloads 1.8.11 and then links 1.8.10? I think we are doing the way how versions are handled wrong. I need to do some research.

Obviously, something in homebrew changed that we are not aware of.

**Comment by 5chdn** [comment]
please try again with:

    brew upgrade --verbose

and share the full logs here please

**Comment by k06a** [comment]
1. Currently installed version is 1.8.10 with command `brew install parity --stable`
2. I don't know why `brew upgrade` see currently not `stable` 1.9.3 version
3. Homebrew trying to install latest stable version: 1.8.11

```
$ brew upgrade --verbose
```
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (paritytech/paritytech).
==> Updated Formulae
paritytech/paritytech/parity ✔
```
Trying to run it:
```
$ parity
```
```
-bash: /usr/local/bin/parity: Permission denied
```
Trying to uninstall:
```
$ brew uninstall parity
```
```
Uninstalling /usr/local/Cellar/parity/1.8.10... (4 files, 38MB)
parity 1.8.11 1 is still installed.
Remove all versions with `brew uninstall --force parity`.
```
Trying to uninstall with force:
```
$ brew uninstall --force parity
```
Uninstalling parity... (2 files, 38.2MB)
```
Trying to install again:
```
$ brew install parity --stable
```
```
==> Installing parity from paritytech/paritytech
==> Downloading https://d1h4xl4cr1h0mo.cloudfront.net/v1.8.11/x86_64-apple-darwin/parity
Already downloaded: /Users/k06a/Library/Caches/Homebrew/parity-1.8.11.11
==> Caveats
To have launchd start paritytech/paritytech/parity now and restart at login:
  brew services start paritytech/paritytech/parity
==> Summary
🍺  /usr/local/Cellar/parity/1.8.11: 4 files, 38.2MB, built in 2 seconds
```
And finally:
```
$ brew upgrade --verbose
```
```
[no output]
```
Wow!
```
$ parity --version
```
```
Parity
  version Parity/v1.8.11-stable-21522ff-20180227/x86_64-macos/rustc1.24.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

Ok, I don't know how the issue was resolved, because until 1.8.11 version reinstall did not helped – tried a lot of times.

**Comment by k06a** [comment]
@5chdn looks like you changed some conditions in `parity.rb`, I think this helped. Thanks!

**Comment by 5chdn** [comment]
Yes I think our issue is that the default version was higher than the stable version, this confused homebrew internally not passing the stable flag to all subcommands. let me know if this returns
