### ISSUE TITLE
This formula has no `--version=` option

### ISSUE THREAD

**Issue by maurelian** [paritytech/homebrew-paritytech#79]
As a user, I want to install a previous version of parity:

```
$ brew install paritytech/paritytech/parity --version=1.9.5
==> Installing parity from paritytech/paritytech
Warning: paritytech/paritytech/parity: this formula has no --version= option so it will be ignored!
==> Downloading https://d1h4xl4cr1h0mo.cloudfront.net/v1.10.8/x86_64-apple-darwin/parity
###########
```

**Comment by debris** [comment]
`--version` option is totally optional for brew formulas and it's not a commonly used pattern.

for more info read:

https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

We will not support installing specific version via brew
